### ISSUE TITLE
Failing to initialize the pressure sensor

### ISSUE THREAD

**Issue by RyanParsley** [cardonabits/haxo-rs#13]
When I attempt to run the software I see the following error.

thread 'main' panicked at 'Failed to initialize pressure sensor: Io(Os { code: 121, kind: Uncategorized, message: "Remote I/O error" })', src/main.rs:88:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

When I run with the backtrace, I just see seg fault added to the output.

**Comment by jcard0na** [comment]
Hi @RyanParsley,

This error indicates a problem communicating with the sensor over I2C.  Did you enable I2C on the Raspberry Pi? (See the fourth step [here](https://github.com/cardonabits/haxo-hw/blob/main/docs/development.md#initial-configuration)).  Let's hope that solves it.   Otherwise it could be a faulty sensor.

**Comment by jcard0na** [comment]
Hi @RyanParsley,

Is this still an issue?

Thanks,

**Comment by RyanParsley** [comment]
No, this is not still an issue. I'm unclear on what the cause was, but feels like it was likely a PEBKAC class issue.
