### ISSUE TITLE
Play sound to indicate haxo started successfully

### ISSUE THREAD

**Issue by jcard0na** [cardonabits/haxo-rs#4]
Boot times vary from device to device and currently they are only audible as a 'pop' from the audio driver.  
It would be better to indicate that the haxophone is ready to play by playing a couple of notes.

**Comment by gerdb** [comment]
I've created a fork which plays a short midi at startup using fluidsynth and also created a midi file. [MP3 preview](https://github.com/gerdb/haxo-rs/raw/play-startup-midi/midi/startup/Startup_Haxophone.mp3)
![image](https://raw.githubusercontent.com/gerdb/haxo-rs/play-startup-midi/midi/startup/Startup_Haxophone.png)
https://github.com/gerdb/haxo-rs/tree/play-startup-midi
I didn't start a pull request because I don't know if or how you want to realize this feature. So see it as an example or inspiration. But of course you can use the midi file (CC0)
[source code](https://github.com/gerdb/haxo-rs/commit/636afd13ef67ebd5fe1d9ec5dad143261dd593a5)

**Comment by jcard0na** [comment]
Hey, this is great!  If you want to start the pull request, I'll be happy to pull this into master.
One question:  does this mitigate in any way the starting 'pop'?  Or do you still hear the 'pop' before the startup midi?
That audible 'pop' is something I would really like to fix, but I have not been able to find a solution.

**Comment by gerdb** [comment]
_"does this mitigate in any way the starting 'pop'"_
Unfortunately not. I've added a short rest before playing the first note so that the first note does not start with this pop.

**Comment by jcard0na** [comment]
I just merged your PR.  Thanks @gerdb!
